services:
  - type: web
    name: nakshatra-interiors-mvp
    runtime: static
    buildCommand: cd frontend && yarn install && yarn build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
